- README.md
- __tests__/index.test.js
- classes/NextPage.js
- classes/__tests__/NextPage.test.js
- examples/basic-next-serverless-app/pages/categories/uno/dos.js
- index.js
- integration/__tests__/local-deploy.test.js
- integration/__tests__/package.test.js
- integration/app-with-serverless-offline/pages/categories/fridge/fridges.js
- integration/basic-app/pages/blog/index.js
- integration/basic-app/pages/categories/fridge/fridges.js
- lib/__tests__/copyBuildFiles.test.js
- lib/__tests__/getCompatLayerCode.test.js
- lib/__tests__/getNextPagesFromBuildDir.test.js
- lib/__tests__/uploadStaticAssetsToS3.test.js
- lib/copyBuildFiles.js
- lib/getCompatLayerCode.js
- lib/getNextPagesFromBuildDir.js
- lib/rewritePageHandlers.js
Fixes https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/23
Maybe fixes https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/24
> feat: add support for nested page directories

- .eslintignore
- .travis.yml
- classes/NextPage.js
- classes/__tests__/NextPage.test.js
- integration/__tests__/package.test.js
- integration/app-with-serverless-offline/.serverless_plugins/serverless-nextjs-plugin.js
- integration/app-with-serverless-offline/package.json
- integration/basic-app-with-nested-next-config/app/next.config.js
- integration/basic-app-with-nested-next-config/app/pages/about.js
- integration/basic-app-with-nested-next-config/app/pages/blog/index.js
- integration/basic-app-with-nested-next-config/app/pages/categories/fridge/fridges.js
- integration/basic-app-with-nested-next-config/app/pages/home.js
- integration/basic-app-with-nested-next-config/app/pages/post.js
- integration/basic-app-with-nested-next-config/serverless.yml
- jest.integration.setup.js
- lib/__tests__/getNextPagesFromBuildDir.test.js
- lib/getNextPagesFromBuildDir.js
- utils/test/serverlessOfflineStart.js
Fixes https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/27
> Nested next.config.js

- packages/serverless-nextjs-plugin/lib/__tests__/addCustomStackResources.test.js
- packages/serverless-nextjs-plugin/lib/addCustomStackResources.js
- packages/serverless-nextjs-plugin/utils/test/ServerlessPluginBuilder.js
Related https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/73
> fix: use region in bucket url when required

- integration/__tests__/package.test.js
- packages/serverless-nextjs-plugin/classes/NextPage.js
- packages/serverless-nextjs-plugin/classes/__tests__/NextPage.test.js
- packages/serverless-nextjs-plugin/lib/__tests__/addCustomStackResources.test.js
- packages/serverless-nextjs-plugin/lib/__tests__/build.test.js
- packages/serverless-nextjs-plugin/lib/addCustomStackResources.js
- packages/serverless-nextjs-plugin/utils/test/ServerlessPluginBuilder.js
Fixes https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/80
> Fix custom resources

- packages/serverless-nextjs-plugin/__tests__/index.test.js
- packages/serverless-nextjs-plugin/index.js
- packages/serverless-nextjs-plugin/lib/__tests__/checkForChanges.test.js
- packages/serverless-nextjs-plugin/lib/checkForChanges.js
Validates an assets bucket exists before uploading assets.
> feat: add assets bucket validation

- packages/serverless-nextjs-plugin/__tests__/single-api.test.js
- packages/serverless-nextjs-plugin/classes/NextPage.js
Fixes danielcondemarin/serverless-nextjs-plugin#134 danielcondemarin/serverless-nextjs-plugin#129
> Fix api gateway methods with ANY

- packages/serverless-nextjs-component/package.json
> Update @serverless/domain to 6.1.0. No breaking changes.

- packages/serverless-nextjs-component/examples/multiple-instance-environment/.gitignore
- packages/serverless-nextjs-component/examples/multiple-instance-environment/README.md
- packages/serverless-nextjs-component/examples/multiple-instance-environment/env-prod
- packages/serverless-nextjs-component/examples/multiple-instance-environment/env-staging
- packages/serverless-nextjs-component/examples/multiple-instance-environment/next.config.js
- packages/serverless-nextjs-component/examples/multiple-instance-environment/package.json
- packages/serverless-nextjs-component/examples/multiple-instance-environment/pages/index.js
- packages/serverless-nextjs-component/examples/multiple-instance-environment/serverless.js
- packages/serverless-nextjs-component/examples/multiple-instance-environment/serverless.yml
A proper solution for #177. This is the preferred way of doing things (I have had lots of back and forth with both the serverless core engineers and collaborators - see https://github.com/serverless/components/issues/481)
@danielcondemarin One thing that I do not have is any domain in Route53. Could you please test this with any domain you have lying around.
> example of multiple instances (stages)

- packages/serverless-nextjs-component/__tests__/assets.test.js
- packages/serverless-nextjs-component/package-lock.json
- packages/serverless-nextjs-component/package.json
- packages/serverless-nextjs-component/serverless.js
> cache build assets for component

- packages/serverless-nextjs-component/.gitignore
- packages/serverless-nextjs-component/__tests__/build-dynamic-routes-precedence.test.js
- packages/serverless-nextjs-component/__tests__/build.test.js
- packages/serverless-nextjs-component/__tests__/default-lambda-handler.test.js
- packages/serverless-nextjs-component/__tests__/deploy.test.js
- packages/serverless-nextjs-component/__tests__/fixtures/app-with-no-static-or-public-directory/serverless.yml
- packages/serverless-nextjs-component/__tests__/fixtures/default-build-manifest.json
- packages/serverless-nextjs-component/__tests__/fixtures/dynamic-routes-precedence/.next/serverless/pages-manifest.json
- packages/serverless-nextjs-component/__tests__/fixtures/simple-app/.next/serverless/pages-manifest.json
- packages/serverless-nextjs-component/__tests__/fixtures/simple-app/serverless.yml
- packages/serverless-nextjs-component/default-lambda-handler.js
- packages/serverless-nextjs-component/lib/sortedRoutes.js
- packages/serverless-nextjs-component/serverless.js
Fixes https://github.com/danielcondemarin/serverless-next.js/issues/235, https://github.com/danielcondemarin/serverless-next.js/issues/224, https://github.com/danielcondemarin/serverless-next.js/issues/212
> feat(component): dynamic routes rendered from static pages

- packages/serverless-nextjs-component/api-lambda-handler.js
found a small typo here, this declares the route variable as local
> fix variable of lamda function

- packages/serverless-nextjs-component/serverless.js
I think this should account for the new case outlined in the docs.
Fixes #266
> Properly default build.enabled

- packages/serverless-nextjs-component/__tests__/build.test.js
- packages/serverless-nextjs-component/__tests__/default-lambda-handler.test.js
- packages/serverless-nextjs-component/__tests__/fixtures/built-artifact/pages/customers/[...catchAll].js
- packages/serverless-nextjs-component/__tests__/fixtures/built-artifact/pages/customers/[customer]/profile.js
- packages/serverless-nextjs-component/__tests__/fixtures/default-build-manifest.json
- packages/serverless-nextjs-component/__tests__/fixtures/simple-app/.next/serverless/pages-manifest.json
- packages/serverless-nextjs-component/examples/dynamodb-crud/package.json
- packages/serverless-nextjs-component/lib/expressifyDynamicRoute.js
- packages/serverless-nextjs-component/lib/sortedRoutes.js
- packages/serverless-nextjs-component/serverless.js
Implements https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes
Closes https://github.com/danielcondemarin/serverless-next.js/issues/286
> Catch all dynamic routes

- packages/serverless-nextjs-component/__tests__/next-aws-cloudfront.response.test.js
- packages/serverless-nextjs-component/next-aws-cloudfront.js
Closes https://github.com/danielcondemarin/serverless-next.js/issues/287
> Handle res.setHeader with array of values

- package.json
- packages/lambda-at-edge/src/build.ts
- packages/lambda-at-edge/src/default-handler.ts
- packages/lambda-at-edge/src/types.d.ts
- packages/lambda-at-edge/tests/build/build.test.ts
- packages/lambda-at-edge/tests/build/simple-app-fixture/.next/BUILD_ID
- packages/lambda-at-edge/tests/build/simple-app-fixture/next.config.js
- packages/lambda-at-edge/tests/default-handler/default-build-manifest.json
- packages/lambda-at-edge/tests/default-handler/default-handler.test.ts
- packages/lambda-at-edge/tests/dynamic-routes-precedence/fixture/.next/BUILD_ID
- packages/lambda-at-edge/tests/dynamic-routes-precedence/fixture/next.config.js
- packages/lambda-at-edge/tests/integration/with-empty-next-config/with-empty-next-config.test.ts
- packages/lambda-at-edge/tests/integration/with-next-build-failure/with-next-build-failure.test.ts
- packages/lambda-at-edge/tests/public-and-static-dir/app-with-no-static-or-public-dir-fixture/.next/BUILD_ID
- packages/lambda-at-edge/tests/public-and-static-dir/app-with-no-static-or-public-dir-fixture/next.config.js
- packages/lambda-at-edge/tests/serverless-trace/fixture/.next/BUILD_ID
- packages/lambda-at-edge/tests/shared-fixtures/built-artifact/pages/customers/[customer].js
- packages/lambda-at-edge/tests/shared-fixtures/built-artifact/pages/customers/[customer]/profile.js
- packages/lambda-at-edge/tests/shared-fixtures/built-artifact/pages/customers/index.js
- packages/lambda-at-edge/tests/test-utils.ts
- packages/serverless-component/__tests__/custom-inputs.test.js
- packages/serverless-component/__tests__/deploy.test.js
- packages/serverless-component/serverless.js
Implements `getServerSideProps` proposed in https://github.com/danielcondemarin/serverless-next.js/issues/355
> getServerSideProps support

- packages/lambda-at-edge/src/api-handler.ts
- packages/lambda-at-edge/src/build.ts
- packages/lambda-at-edge/tests/api-handler/api-handler.test.ts
- packages/lambda-at-edge/tests/build/build.test.ts
> return a 404 status code for not-found api-lambda route requests

- packages/lambda-at-edge/src/default-handler.ts
- packages/lambda-at-edge/tests/default-handler/default-handler.test.ts
Fixes https://github.com/serverless-nextjs/serverless-next.js/issues/496
> chore: fix s3 bucket not being normalized for public assets

- README.md
Adding the example link to the ReadMe
> Adding example links

- packages/aws-lambda/serverless.js
- yarn.lock
- removes aws-lambda-layer usage
- removes aws-s3 usage
> Cleanup aws-lambda component

- packages/lambda-at-edge/src/default-handler.ts
Fixes https://github.com/serverless-nextjs/serverless-next.js/issues/522
> Fix root uri normalisation issue in next 9.5

- packages/libs/lambda-at-edge/src/build.ts
This is a fix for https://github.com/serverless-nextjs/serverless-next.js/issues/568 where it fails the build step when `next.config.js` is defined using `next-compose-plugins` because it expected an object instead of `undefined` when called.
In my previous change to support trailing slash redirects, I had executed `next.config.js`'s export if it was a function during the build, but had not passed any arguments, so it would fail to deploy when using `next.config.js` with certain plugins such as `next-compose-plugins`, because this specific plugin was expecting a non-undefined `defaultConfig` object. This affects all deploys that used this plugin, even if they didn’t use trailing slash config.
As defined here, `next.config.js` may have two arguments: …
> fix(lambda-at-edge): fix reading next.config.js in build step when it exports a function

- packages/serverless-components/nextjs-component/src/component.ts
> Fix Remove: wait sequentially for resources to be removed to avoid race conditions

- README.md
* Code size guidance
* Lambda timeouts guidance
> docs: update FAQs

- README.md
> docs: add FAQ about Host header, update references to component input

- .github/ISSUE_TEMPLATE/bug_report.md
* Make it more specific and have helpful links in the checklist
* Put the hints in comment brackets so it's cleaner
> docs: clean up the bug report template

- packages/serverless-components/domain/serverless.js
Fixes the DNS creation error where hosted zone is configured in a different account.
closes #632
> Create the DNS record only when hosted zone exits

- packages/serverless-components/nextjs-component/src/component.ts
This should fix: https://github.com/serverless-nextjs/serverless-next.js/issues/682
Manually tested and verified that default values for `_next/data/*` can be overridden.
> fix(nextjs-component): fix inability to set custom behavior for _next/data/*

- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/tests/build/build.test.ts
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/.next/BUILD_ID
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/.next/cache/placeholder.txt
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/.next/prerender-manifest.json
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/.next/routes-manifest.json
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/.next/serverless/pages-manifest.json
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-public-static-error/next.config.js
* This conflicts with `static/*` cache behavior so we should fail the build in this case.
Added a unit test.
> fix(lambda-at-edge): fail build when "public/static" folder exists as this conflicts with static/* cache behavior

- packages/e2e-tests/next-app-dynamic-routes/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-dynamic-routes/pages/optional-catch-all-ssr/[[...catch]].tsx
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/src/lib/expressifyDynamicRoute.ts
- packages/libs/lambda-at-edge/src/lib/isDynamicRoute.ts
- packages/libs/lambda-at-edge/tests/build/build.test.ts
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture/.next/serverless/pages-manifest.json
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/523
Will add more e2e tests for catch-alls in general (and fix some other bugs) in another PR.
> feat(lambda-at-edge): support optional catch-all

- README.md
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
This is my attempt at extending the functionality proposed in #603 to allow skipping on empty paths.
Also, added tests for the new functionality.
> Add invalidation paths config and tests

- packages/e2e-tests/next-app-using-serverless-trace/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-base-path/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-trailing-slash/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/prev-next-app-with-base-path/cypress/integration/rewrites.test.ts
- packages/e2e-tests/prev-next-app-with-trailing-slash/cypress/integration/rewrites.test.ts
- packages/e2e-tests/prev-next-app/cypress/integration/rewrites.test.ts
Follow up to: https://github.com/serverless-nextjs/serverless-next.js/pull/812
> test(e2e-tests): fix rewrite e2e tests

- packages/libs/lambda-at-edge/package.json
May fix: https://github.com/serverless-nextjs/serverless-next.js/issues/840
> fix(lambda-at-edge): try to copy all files in sharp_node_modules

- packages/e2e-tests/next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app/serverless.yml
- packages/libs/lambda-at-edge/src/routing/rewriter.ts
Should fix: https://github.com/serverless-nextjs/serverless-next.js/issues/863
> fix(lambda-at-edge): pass body correctly into external rewrite

- packages/libs/lambda-at-edge/README.md
- update related to new configurable inputs
> Update for README.md

- packages/libs/lambda-at-edge/src/routing/redirector.ts
Fix for: https://github.com/serverless-nextjs/serverless-next.js/issues/933
> fix(lambda-at-edge): fix language detection

- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
Enable passing deploy and build.enabled flags as environment variables (#999)
> Enable passing deploy and build.enabled flags as environment variables (#999)

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
> Test for and fix external trailing hash redirects

- packages/libs/core/src/redirect.ts
Fixes #1105 
This feature could use some negative-case unit tests and _any_ e2e tests.
> Fix accept language redirect condition

- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
Instead of one role ARN for all Lambdas
> fix(nextjs-component): allow specifying role arn for each lambda

- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-locales/cypress/integration/redirects.test.ts
- packages/libs/core/src/route/redirect.ts
* Also added some tests to ensure no infinite redirects on locale paths when Accept-Language or NEXT_LOCALE cookie are set
> fix(core): fix infinite redirects on NEXT_LOCALE cookie

- documentation/docs/basics.md
- package.json
- yarn.lock
AFAICT these are all either not needed or are installed explicitly in some of the sub packages.
Edit: slightly too optimistic, added back react for integration tests.
> Drop unused deps

- packages/libs/lambda-at-edge/src/images/imageOptimizer.ts
- packages/libs/lambda-at-edge/tests/image-handler/image-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/image-handler/image-handler.test.ts
- packages/libs/lambda-at-edge/tests/mocks/s3/aws-sdk-s3-client-get-object-command.mock.ts
- packages/libs/lambda-at-edge/tests/mocks/s3/aws-sdk-s3-client.image.mock.ts
May fix: https://github.com/serverless-nextjs/serverless-next.js/issues/1285
> fix(lambda-at-edge): handle /_next/static image requests and minor improvements to image error logging

- .github/workflows/CI.yml
- scripts/comment-handler-sizes.ts
- scripts/get-auth.ts
Closes: https://github.com/serverless-nextjs/serverless-next.js/issues/1314
> chore: use comment proxy api for commenting handler sizes

- packages/libs/lambda-at-edge/src/s3/s3BucketNameFromEventRequest.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-origin-response.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath-origin-response.test.ts
- packages/libs/lambda-at-edge/tests/image-handler/image-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/image-handler/image-handler.test.ts
Issue has been described here: https://github.com/serverless-nextjs/serverless-next.js/issues/1381
> domainName should be checked before replacing

- packages/libs/core/src/route/locale.ts
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1478
> fix(core): locale redirect should not be lowercased

- yarn.lock
Fixes #2394.
I just ran the following command.
```sh
yarn install
git add ./yarn.lock
git commit -m "fix yarn.lock."
```
> fix CircleCI and Github Actions build commands

- packages/libs/core/src/images/imageOptimizer.ts
- packages/libs/core/tests/images/imageOptimizer.test.ts
Fixes #2421 
I've solved this issue by storing a JSON metadata file in a separate `/tmp` directory for each cached image, as it is not suitable to store the header value in the filename.
> Preserve cached image headers in responses served from FS
