serverless-nextjs/serverless-next.js

- .travis.yml
- __tests__/index.test.js
- classes/NextPage.js
- classes/PluginBuildDir.js
- classes/__tests__/NextPage.test.js
- classes/__tests__/PluginBuildDir.test.js
- index.js
- lib/__tests__/copyBuildFiles.test.js
- lib/__tests__/getCompatLayerCode.test.js
- lib/__tests__/getNextPagesFromBuildDir.test.js
- lib/__tests__/rewritePageHandlers.js
- lib/__tests__/uploadStaticAssetsToS3.test.js
- lib/uploadStaticAssetsToS3.js
- utils/test/getServerlessExec.js
Fixes for Windows platform:
- Fixes numerous unit tests assuming only posix filepaths are used
- Fixes integration tests
- Bugfixes where again posix filepaths are assumed to always be the case
> Windows support

- lib/__tests__/getFactoryHandlerCode.test.js
- lib/getFactoryHandlerCode.js
This PR will resolve the relative path to the custom handler when the page is located in a sub-directory.
> fix: resolve relative path to custom handler

- README.md
- lib/__tests__/getNextPagesFromBuildDir.test.js
- lib/getNextPagesFromBuildDir.js
Needed a way to add config to all page functions so added a very simple way of doing so by allowing an asterisk `*` entry in pageConfig that is applied to all functions. The global config can itself be overridden by page-specific config.
> feat: global page config

- README.md
- examples/app-with-custom-lambda-handler/serverless.yml
- examples/basic-next-serverless-app/serverless.yml
- index.js
- integration/app-with-serverless-offline/serverless.yml
- integration/basic-app/serverless.yml
- lib/__tests__/getAssetsBucketName.test.js
assuming most setups will have the `next.config.js` in root, this reduces configuration overhead for default setup.
fix https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/68
> Use "./" as default value for nextConfigDir

- classes/NextPage.js
- classes/__tests__/NextPage.test.js
- integration/__tests__/package.test.js
- lib/__tests__/build.test.js
- lib/__tests__/rewritePageHandlers.js
- lib/getNextPagesFromBuildDir.js
- lib/rewritePageHandlers.js
In order to not cause conflicts between pages with same name in different folders.
ref https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/67
We might have a few pageIds with `$` in the future so while I was at it, I added a normalisation for the function name in oder to not break CloudFormation-Ressource names.
PTAL: @danielcondemarin
> Use pageId as identifier 

- packages/serverless-nextjs-plugin/lib/addCustomStackResources.js
Adding a route with unparsed non-alphanumeric characters (e.g. `favicon-32x32.png`) to `serverless.yml` would cause AWS to throw "Resource name is non alphanumeric" error.
> fix: parse non-alphanumeric characters in resourceName

- README.md
- packages/serverless-nextjs-plugin/README.md
- packages/serverless-nextjs-plugin/index.js
- packages/serverless-nextjs-plugin/lib/__tests__/addCustomStackResources.test.js
- packages/serverless-nextjs-plugin/lib/addCustomStackResources.js
- packages/serverless-nextjs-plugin/lib/checkForChanges.js
- packages/serverless-nextjs-plugin/resources/cloudfront.yml
- packages/serverless-nextjs-plugin/utils/test/ServerlessPluginBuilder.js
Currently, API Gateway is being used as a proxy to S3 to serve static assets from `/static` and `/public` directories. Whilst this works, is not the best solution as API Gateway is not as cost effective as CloudFront, nor is designed to be used as a CDN.
Also CloudFront comes with features such as compression, logging, domains, certificates etc. 
```yml
custom:
serverless-nextjs:
assetsBucketName: cloudfront.isawesome
cloudFront: true
```
When `cloudFront` flag is set to true, a CloudFront distribution is created with API Gateway and S3 as origins. `_next` build assets and `static/` or `public/` folder assets are served from the S3 origin. Page requests, such as `/blog/:post` are served from the API Gateway origin.  
This article was used as a reference for implementation: …
> CloudFront Support

- README.md
- packages/serverless-nextjs-plugin/index.js
- packages/serverless-nextjs-plugin/lib/addCustomStackResources.js
- packages/serverless-nextjs-plugin/lib/checkForChanges.js
This PR will add the option `createAssetBucket` with the default value set to `true`. It also fixes some issues where it would fail to deploy if the bucketName was resolved to `null` or `undefined`.
This fixes #100 and potentially #102 and #86 as well. It's also a workaround for #103 since it allows you to manually set up your bucket with unique resource names.
> Feature: Add option to disable bucket creation

- packages/serverless-nextjs-plugin/lib/__tests__/build.test.js
- packages/serverless-nextjs-plugin/lib/build.js
- packages/serverless-nextjs-plugin/package.json
This addresses #124 and #75. It allows `next-aws-lambda` to be found by determining where `node_modules` is relative to the `nextConfigDir`. It uses the very popular (and battle tested) `findup-sync` module to determine the *node_modules* folder.
> Allows next-aws-lambda to be found relative to node_modules

- packages/serverless-nextjs-plugin/lib/__tests__/build.test.js
- packages/serverless-nextjs-plugin/lib/build.js
- packages/serverless-nextjs-plugin/package.json
This solution is more generalized than the previous one. It removes `findup-sync` and instead relies upon require.resolve. This fixes #75 and #124
> Fix: allow 'next-aws-lambda' to be found using require.resolve

- packages/next-aws-lambda/README.md
- packages/next-aws-lambda/__tests__/index.test.js
- packages/next-aws-lambda/index.js
- packages/next-aws-lambda/lib/__tests__/compatLayer.response.test.js
- packages/next-aws-lambda/lib/compatLayer.js
- packages/serverless-nextjs-plugin/lib/getFactoryHandlerCode.js
`next-aws-lambda` now supports async promises:
```js
// using async promise
module.exports.render = async (event, context, callback) => {
const responsePromise = compat(page)(event, context); // don't pass the callback parameter
return responsePromise;
};
```
Also updated usage in the plugin to use this approach.
Closes https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/125
> next-aws-lambda can now be consumed using async signature

- packages/serverless-nextjs-component/next-aws-cloudfront.js
Resolves #155 by using the `response.status` value instead of `response.statusCode`.
Previously, setting the value of `response.statusCode` didn't have an effect since CloudFront uses `response.status`. This meant that all routes returned a 200 status code even if the route did not exist.
It looks like `response.statusCode` might have been a typo since `statusCode` isn't an actual property on `response`.
> Fixes response status code not being set properly

- packages/serverless-nextjs-component/README.md
- packages/serverless-nextjs-component/__tests__/build.test.js
- packages/serverless-nextjs-component/__tests__/custom-domain.test.js
- packages/serverless-nextjs-component/serverless.js
Closes #145 by exposing a configuration option for the S3 bucket name the component creates.
Looks like the input isn't documented in the `@serverless/aws-s3` component, however the input configuration for `name` is used [here](https://github.com/serverless-components/aws-s3/blob/master/serverless.js#L27). If the bucket name isn't specified, the component generates a bucket name as it does currently.
> Add configuration for bucket name

- packages/serverless-nextjs-component/package.json
Upgrading to the latest CloudFront plugin allows for cookie forwarding and other options.
It may be worth considering exposing some inputs (with sensible defaults) to further configure CloudFront, but for now this will address the issue described in #154.
> Update CloudFront component to latest

- packages/serverless-nextjs-component/__tests__/build.test.js
- packages/serverless-nextjs-component/serverless.js
This PR adds forwarding for cookies and query strings since aren't forwarded in the CloudFront component by default. Fixes #154.
> Forward cookies and query strings to edge lambda

- packages/serverless-nextjs-component/package.json
Update aws-s3 component since any versions < 4.0.0 have a problem uploading directories on windows.
No breaking changes between 3.1.0 and 4.0.0
> Update aws-s3 component

- packages/serverless-nextjs-component/next-aws-cloudfront.js
A common way to do redirections in `getInitialProps` is to use `res.writeHead` and then call `res.end`. When doing this the lambda handler would end up resolving twice and causing an error. This is because next checks if `res.finished` is set before ending the response, but `next-aws-cloudfront` never sets it. This adds `res.finished` and sets it to true in `res.end`.
> Fix calling `res.end` in `getInitialProps`

- packages/serverless-nextjs-component/__tests__/assets.test.js
- packages/serverless-nextjs-component/__tests__/build.test.js
- packages/serverless-nextjs-component/serverless.js
This allows for multiple environments by introducing a new "code root" input. Based largely on the example provided here: https://github.com/serverless/components/issues/481#issuecomment-527848024
Essentially a project can have multiple serverless.yml files in sub folders that reference the root directory like so:
```
myNextApp:
component: serverless-next.js
inputs:
code:
root: ../
```
I left the structure like this in part to mimic what is done in [serverless/backend](https://github.com/serverless-components/backend/blob/master/serverless.js#L25) and also to potentially allow for [custom build directories](https://nextjs.org/docs#setting-a-custom-build-directory). Though for simplicity it could be renamed to inputs->code or inputs ->root to avoid the unnecessary nesting.
This solves #177 …
> Multiple environment support

- packages/serverless-nextjs-plugin/lib/__tests__/uploadStaticAssets.test.js
- packages/serverless-nextjs-plugin/lib/uploadStaticAssets.js
- packages/serverless-nextjs-plugin/utils/s3/__tests__/upload.test.js
- packages/serverless-nextjs-plugin/utils/s3/upload.js
Adds cache-control metadata to build assets. Infrastructure for adding cache-control for public and static folders can be used, however we can chat about how to implement configs for this in the serverless.yml config. This should address #40
> Adding cache control to build assets

- packages/serverless-nextjs-component/__tests__/deploy.test.js
- packages/serverless-nextjs-component/serverless.js
This should fix query and cookies for cloudfront default cache behaviour according to `@serverless/aws-cloudfront` [docs](https://github.com/serverless-components/aws-cloudfront#3-configure)
I need some instructions to run and test it but it should work
> Fix cloudfront default cache behavior

- packages/serverless-nextjs-component/README.md
- packages/serverless-nextjs-component/__tests__/custom-inputs.test.js
- packages/serverless-nextjs-component/examples/multiple-instance-environment/env-prod
- packages/serverless-nextjs-component/examples/multiple-instance-environment/env-staging
- packages/serverless-nextjs-component/examples/multiple-instance-environment/serverless.yml
- packages/serverless-nextjs-component/lib/obtainDomains.js
- packages/serverless-nextjs-component/serverless.js
This solves #228.
It alters the code so that it does not assume an array with two elements, with the first being a subdomain. If subdomain is not present, it will be hard coded to "www", which will not be needed for root if present (see https://github.com/serverless-components/domain/blob/master/serverless.js#L213)
I believe that this will make things more intuitive
> ignore subdomain if not present

- packages/serverless-nextjs-component/__tests__/assets.test.js
- packages/serverless-nextjs-component/serverless.js
I noticed the Cache-Control metadata information in the files uploaded to s3 has a typo:
browser headers:
This PR fixes that, as can be seen here:
cheers!
> fix cache header for s3 files

- README.md
Otherwise, it sounds as if you _have_ to create a `.env` file (which is inconvenient for CI purposes).
> Clarify that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY can be set as environment variables

- packages/next-aws-lambda/lib/compatLayer.js
I noticed intermittent errors in CloudWatch after deploying my Next.js app with `serverless-nextjs-plugin`. The stacktrace pointed at this line, so I added a guard to ensure `response.body` wouldn't cause an exception with `Buffer.concat`. I verified the errors no longer occur after redeploying with this fork.
Not sure why it only happened intermittently, but let me know if I missed something obvious. Thanks!
```
ERROR	TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be one of type Array, Buffer, or Uint8Array. Received type string
at Function.concat (buffer.js:480:13)
at Stream.res.write.chunk [as write] (/var/task/node_modules/next-aws-lambda/lib/compatLayer.js:80:28)
at Stream.text [as end] (/var/task/node_modules/next-aws-lambda/lib/compatLayer.js:99:19)
at sendHTML …
```
> Convert non-Buffer response.body to Buffer

- packages/next-aws-lambda/lib/__tests__/compatLayer.request.test.js
- packages/next-aws-lambda/lib/compatLayer.js
To fix #314 
`req.url` should never be an empty string, so default to `"/"`.
> Fix for empty req url

- packages/next-aws-lambda/lib/__tests__/compatLayer.response.test.js
- packages/next-aws-lambda/lib/compatLayer.js
When deploying to netlify or AWS (both depend on AWS-lambda)
The SSR components (using `getServerSideProps` fails with the following
error:
```
ERROR	TypeError: res.hasHeader is not a function
at sendPayload (/var/task/pages/test.js:5787:41)
at renderReqToHTML (/var/task/pages/test.js:1773:13)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Module.render (/var/task/pages/test.js:1816:22)
```
This is caused by nextjs trying to use the default node `hasHeader`
method here: https://github.com/zeit/next.js/blob/v9.3.1/packages/next/next-server/server/send-payload.ts#L25
This commit fix the issue reported here: https://github.com/zeit/next.js/issues/11223
which I could verify also happening on our stack by adding the method
that mimics the nodeJS method (using …
> Fix the issue with TypeError hasHeader is not a function

- packages/next-aws-lambda/lib/__tests__/compatLayer.response.test.js
- packages/next-aws-lambda/lib/compatLayer.js
Previously the following behaviour could be observed:
```
res.setHeader("X-CUSTOM", "VAL")
res.getHeader("X-CUSTOM") => null
res.hasHeader("X-CUSTOM") => false
res.setHeader("x-custom", "val")
res.getHeader("X-CUSTOM") => "val"
res.hasHeader("X-CUSTOM") => true
```
There is no way of accessing a header that isn't set in lower case,
This fixes the issue by always storing the header name as lower case,
allowing a similar behaviour to node HTTP ResponseObject behaviour
- https://nodejs.org/api/http.html#http_request_getheader_name
- https://nodejs.org/api/http.html#http_request_removeheader_name
- https://nodejs.org/api/http.html#http_request_setheader_name_value
> Bug/header-name case-sensitive

- packages/serverless-nextjs-component/default-lambda-handler.js
Removes the warning viewing in the lambda console.
Using `let` to match https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-nextjs-component/api-lambda-handler.js#L16 although I think both can be `const`?
> Add let to iteration in default-lambda-handler

- packages/serverless-component/README.md
- packages/serverless-component/__tests__/custom-inputs.test.js
- packages/serverless-component/serverless.js
Allows you to pass `origins` to `aws-cloudfront` as well as setting headers for `api` and `defaults` etc.
We do this commonly for redirects and also for legacy parts of sites that request static from particular urls.
> Pass through cloudfront.origins inputs and expand relative paths

- .gitignore
- packages/apigw-lambda-compat/lib/__tests__/compatLayer.request.test.js
- packages/apigw-lambda-compat/lib/compatLayer.js
- packages/lambda-at-edge-compat/__tests__/next-aws-cloudfront.request.test.js
- packages/lambda-at-edge-compat/next-aws-cloudfront.js
- packages/lambda-at-edge-compat/package-lock.json
Closes https://github.com/danielcondemarin/serverless-next.js/issues/384
For testing, I've added the below lines to my `serverless.yml` file just like explained in [CONTRIBUTING.md](https://github.com/danielcondemarin/serverless-next.js/blob/47fb657f49ba68cd79a8b8b4328c797bda9e7d24/CONTRIBUTING.md#testing-the-plugin-on-a-serverless-application):
```yaml
plugins:
localPath: "/home/mertyildiran/Downloads/serverless-next.js/packages/serverless-plugin"
modules:
- index
```
and deployed to AWS CloudFront but I think it didn't use my fork. I also tried to directly edit from `node_modules` but I think it didn't take any effect too. Probably I'm doing something wrong in the local development process.
I'm opening this PR because the tests I've added show that it works. @danielcondemarin if you …
> Copy the properties of http.IncomingMessage.prototype to request object by deep cloning

- packages/serverless-component/__tests__/custom-inputs.test.js
- packages/serverless-component/serverless.js
Hey, I just found a few bugs when I went to use the custom cloudfront configs.
1. custom configs for `static/*` may fail validation because there wont be any pages at these paths (the same for `_next/*`)
2. The nodejs AWS SDK will throw an error if you have an undefined value for a key, meaning we need to preprocess the values
correct me if im wrong, but we have tests for the second case, i think the mock API behaves differently
> Custom cloudfront bug fixes

- packages/lambda-at-edge/src/default-handler.ts
- packages/lambda-at-edge/tests/default-handler/default-handler.test.ts
- I ran into some issues when I started forwarding the `Host` header from cloudfront. It causes signature invalidation on the request because the host is used to generate the signature
- https://github.com/danielcondemarin/serverless-next.js/issues/408
- Explicitly set the host header when forwarding requests to S3 origin
- Tested on my own website. Confirmed the fix
> Explicitly set host header for s3 origin

- packages/s3-static-assets/src/index.ts
- packages/s3-static-assets/src/lib/constants.ts
- packages/s3-static-assets/tests/upload-assets.test.ts
The serverless component is not preventing clients (e.g. browsers) from caching static pages locally. We have to prevent this behaviour, since static pages have references to chunks and other static files that are generated per app build. If a static page gets cached locally and a new version is deployed, clients that have a static page cached will be referencing assets from a previous version/build and this may lead to unexpected errors. Vercel Edge Network, for example, returns by default a `Cache-Control` header containing `public, max-age=0, must-revalidate` for static files (see [docs](https://vercel.com/docs/v2/edge-network/caching#static-files)).
With this PR, `serverless-next.js` will add a `Cache-Control: no-store` header to static page objects uploaded to S3, preventing them …
> Prevent client cache of static pages

- packages/apigw-lambda-compat/lib/__tests__/compatLayer.response.test.js
- packages/apigw-lambda-compat/lib/compatLayer.js
- packages/lambda-at-edge-compat/__tests__/next-aws-cloudfront.response.test.js
- packages/lambda-at-edge-compat/next-aws-cloudfront.js
- Fixes https://github.com/danielcondemarin/serverless-next.js/issues/436 
- Partially fixes https://github.com/danielcondemarin/serverless-next.js/issues/378
> Compat Layer status code fixes

- packages/cloudfront/CHANGELOG.md
- packages/cloudfront/README.md
- packages/cloudfront/package-lock.json
- packages/cloudfront/package.json
- packages/cloudfront/src/index.ts
- packages/cloudfront/src/lib/cloudfront.ts
- packages/cloudfront/src/lib/constants.ts
- packages/cloudfront/tests/aws-sdk.mock.ts
- packages/cloudfront/tests/cache-invalidation.test.ts
- packages/cloudfront/tsconfig.build.json
- packages/cloudfront/tsconfig.json
- packages/s3-static-assets/src/index.ts
- packages/s3-static-assets/src/lib/constants.ts
- packages/s3-static-assets/tests/upload-assets.test.ts
- packages/serverless-component/__mocks__/@sls-next/cloudfront.js
- packages/serverless-component/__tests__/deploy.test.js
- packages/serverless-component/package-lock.json
- packages/serverless-component/package.json
- packages/serverless-component/serverless.js
As reported by #430, static pages are not cached by CloudFront and client requests are always hitting the origin.
Static pages should be automatically cached at the edge after the first request for an arbitrary long period of time. When a new deployment occurs, the CloudFront cache should be invalidated, ensuring that the latest version is served to clients. This gives us the most flexibility, as users get the latest file from CDN immediately after deploying.
- Instead of using `Cache-Control: no-store` for static pages, the component now uses `public, max-age=0, s-maxage=86400, must-revalidate`. This prevents the page from being cached in the browser, but `s-maxage` allows the page to be cached at edge locations for 1 day (86400 seconds). 
- An invalidation request for all paths (`/*`) …
> Cache static pages and invalidate distribution after deploy

- README.md
fixes #280 
I think it's invaluable to keep this info in the README. At least where I work, full admin access to AWS isn't given out to everybody and I had to come up with a more granular list listed here.
> document the full list of AWS permissions required for a deployment

- package-lock.json
- packages/serverless-component/__tests__/custom-inputs.test.js
- packages/serverless-component/__tests__/deploy.test.js
- packages/serverless-component/serverless.js
Without this the cloudfront default behaviour doesn't set compression to true which causes all the responses to the initial page requests to not be gziped. This wastes bandwidth, but worst of all, it brings the Lighthouse performance score down.
Not sure why there's such a large change to the lock file. All I did was run 'npm i'.
> enforce compression for the default cloudfront behaviour

- packages/serverless-component/__tests__/custom-inputs.test.js
- packages/serverless-component/__tests__/deploy.test.js
- packages/serverless-component/serverless.js
> don't forward cookies, headers and query parameters for requests to static paths

- packages/lambda-at-edge-compat/__tests__/next-aws-cloudfront.response.test.js
- packages/lambda-at-edge-compat/next-aws-cloudfront.js
This PR ensures the next-aws-cloudfront compat layer behaves in the same way that nodejs server does when `res.end()` is called more than once. That is, ignore subsequent calls after the first one. 
Fixes  https://github.com/serverless-nextjs/serverless-next.js/issues/316
> Ignore calls to res.end() after the first one

- packages/aws-cloudfront/__tests__/__snapshots__/lambda-at-edge.test.js.snap
- packages/aws-cloudfront/__tests__/lambda-at-edge.test.js
- packages/aws-cloudfront/lib/addLambdaAtEdgeToCacheBehavior.js
I need to set headers for a specific public file so I wanted to setup origin-response or viewer-response for that.
Adding a viewer-response or origin-response causes the following error message:
`InvalidLambdaFunctionAssociation: The IncludeBody option can only be used with viewer-request or origin-request events.`
**To Reproduce**
Steps to reproduce the behavior:
Add to serverless.yml
```
cloudfront:
defaults:
lambda@edge:
viewer-response: <arn>
```
**Desktop (please complete the following information):**
- OS: Windows 10
- Version @sls-next/serverless-component@1.16.0
**Additional context**
Doing something like this...
```
cacheBehavior.LambdaFunctionAssociations.Items.push({
EventType: eventType,
LambdaFunctionARN: lambdaAtEdgeConfig[eventType],
IncludeBody: …
```
> IncludeBody option only with viewer-request or origin-request

- packages/libs/s3-static-assets/src/index.ts
Uploads from Windows had backslashes for the affected groups of files.
> fix(s3-static-assets): Fixed missing posix conversion in s3 uploads.

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-404.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
This fixes routing for basePath URLs and fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/571.
1. Routing/redirects for basePath with index page (and others) did not work correctly (e.g with default settings `/basePath` returned  `/index` which is not a valid path so it returned 404 page and `/basePath/` returned index page).
2. If basePath is expected but unnormalized URL doesn't have it as prefix, serve static 404 page. No redirects are done for these if they have trailing slash or not (same as Next.js)
It looks to be due to the normalization logic where `basePath` becomes empty after removing `basePath`, then returns `/index` after normalization. Then it tries to find a page `/index`, but it doesn't exist, so the SSR 404 page is rendered. With `basePath/`, it …
> fix(lambda-at-edge): proper routing for pages with basePath

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-404.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
- packages/libs/lambda-at-edge/tests/shared-fixtures/built-artifact/pages/_error.js
- packages/libs/lambda-at-edge/tests/shared-fixtures/built-artifact/pages/erroredPage.js
This fixes https://github.com/serverless-nextjs/serverless-next.js/issues/566 and few other improvements:
* 500 page that is part of Next.js (`_error.js`) is rendered instead of CloudFront's 503 when SSR page has an error. It also sets 500 status code so that the message in the page actually says there is a 500 error.
* 404 pages were returning 200 status codes incorrectly, and now return 404 status codes. Similarly, ensured that we passed in 404 status into page render (previously we weren't, though Next.js by default renders 404 page anyway)
FYI: CloudFront will cache 4xx/5xx responses for 1 minute: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages-expiration.html. We could make it less if needed, but I think this is sensible.
Added and updated unit …
> fix(lambda-at-edge): render Next 500 page when SSR render fails, and ensure 404 pages return 404 status codes

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-404.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
This fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/553
* Using Next/Link component to navigate to index page with the new `getServerSideProps` did not do client-side navigation, because the `index.json` retrieval returned 503 error, and Next.js has a fallback to do a server-side navigation. Fixed by updating the routing of `index` data requests.
* Also fixed 503 errors which were due to trying to `require` `404.html` page in the origin response handler when a data request is unmatched. These now go to proper 404 pages.
Updated tests.
On CloudFront:
https://d17ujsvie9w0tw.cloudfront.net/another2/ -> Click on `Home` link, it does client-side navigation.
https://d17ujsvie9w0tw.cloudfront.net/_next/data/kbqVEikVMWVZISeABSsbn/index.json -> returns index json file with …
> fix(lambda-at-edge): fix data request routing / client-side navigation for SSR index page

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-404.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
This fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/576
* Fixes issue in latest alphas (1.17 alpha.8) where public files are served correctly but with 404 status code. This is because in origin response we should only set 404 code on unnormalised uri `/404.html` (these are file URIs returned by the S3 origin).
Added some test cases as well to verify this.
Verified with my app: https://d17ujsvie9w0tw.cloudfront.net/app-store-badge.png (returns 200)
https://d17ujsvie9w0tw.cloudfront.net/notfound/ (returns 404)
https://d17ujsvie9w0tw.cloudfront.net/anotherSSG/ (returns 200)
https://d17ujsvie9w0tw.cloudfront.net/anotherSSR/ (returns 200)
https://d17ujsvie9w0tw.cloudfront.net/ (returns 200)
https://d17ujsvie9w0tw.cloudfront.net/_next/data/jRDzHTftCxGo7bHQ1tybv/index.json …
> fix(lambda-at-edge): fix for 404s on public files

- packages/e2e-tests/next-app/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app/cypress/integration/static-files.test.ts
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
This fixes https://github.com/serverless-nextjs/serverless-next.js/issues/454 and similar issues.
Not sure why we don't allow all CloudFront methods on default caching behavior, which will allow more HTTP methods e.g form posts on SSR pages, similar to Vercel.
This component already adds a policy to the S3 bucket to only allow GetObject from the origin access identity (CloudFront), so requesters cannot modify S3 objects with these additional methods (e.g using DELETE to delete a public file). See: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_AllowedMethods.html
Updated unit and e2e tests, and ran them (e2e tests not yet automated).
SSR page: https://dcrrk28otqvm3.cloudfront.net/ssr-page (allows GET, HEAD, PUT, PATCH, DELETE, POST, OPTIONS). E.g POST/DELETE will return …
> fix(nextjs-component, e2e-tests): allow all CloudFront HTTP methods for default caching behavior

- .github/workflows/CI.yml
- packages/e2e-tests/next-app/package.json
- packages/e2e-tests/next-app/scripts/run-e2e-ci.ts
- packages/e2e-tests/next-app/tsconfig.scripts.json
- packages/e2e-tests/next-app/yarn.lock
This adds e2e tests in the CI workflow. I tested it locally and it works fine, hopefully it works in the CI too (note: it is currently failing due to permissions issue in AWS). This closes https://github.com/serverless-nextjs/serverless-next.js/issues/573.
* It uses a script to:
1. Sync `.serverless` state (to reuse the same distribution) from a deployment S3 bucket.
2. Wait for CloudFront invalidations to complete, Lambda to update, S3 to update, based on the Next.js `BUILD_ID`.
3. Run the Cypress tests (`yarn e2e`) with env variables set for CloudFront URL and `BUILD_ID`.
4. Syncs back `.serverless` state and cleans up app files in `S3`. The Lambda and CloudFront distribution are untouched for future reuse.
* This is run in the 12.x workflow only, and additionally gated using …
> test(e2e-tests): add e2e tests step in CI

- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
This allows setting custom cache behavior for API routes, e.g for api/*. Example config which I tested with `next-app` in the end-to-end tests.
This closes: https://github.com/serverless-nextjs/serverless-next.js/issues/608 and https://github.com/serverless-nextjs/serverless-next.js/issues/532
Tested on the app:
```yml
next-app:
component: "../../serverless-components/nextjs-component"
inputs:
cloudfront:
api/*:
minTTL: 10
maxTTL: 100
defaultTTL: 50
forward:
headers:
[
Host
]
```
This will be reflected in the CloudFront behavior for api/* as follows:
> feat(nextjs-component): allow setting custom API cache behavior

- packages/e2e-tests/next-app/cypress/integration/api-routes.test.ts
- packages/e2e-tests/next-app/cypress/integration/data-requests.test.ts
- packages/e2e-tests/next-app/cypress/integration/static-files.test.ts
- packages/e2e-tests/next-app/cypress/support/commands.ts
- packages/e2e-tests/next-app/pages/api/basic-api.ts
- packages/e2e-tests/next-app/pages/api/nested/[id].ts
This additional test coverage for API routes and other minor updates:
* Basic API
* Dynamic + Nested API
* Add command to check cache response header for whether CloudFront cached it
Tested on my own AWS deployment.
> test(e2e-tests): add initial set of API tests, minor improvements to checking cache status in other tests

- README.md
- packages/serverless-components/nextjs-component/README.md
- packages/serverless-components/nextjs-component/package.json
https://www.npmjs.com/package/@sls-next/serverless-component had an outdated link, also made some minor updates to links in `package.json` and updated wording to be slightly more correct.
> docs: update npm links, description and README

- .github/workflows/CI.yml
Small check to make sure builds on PRs from forks don't run e2e tests as they can't anyway due to no access to the AWS access keys. They will run anyway in the master build. No need to review this.
> chore: don't run e2e tests on forks

- packages/e2e-tests/next-app/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app/next.config.js
- packages/libs/lambda-at-edge/src/api-handler.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-basepath-routes-manifest.json
- packages/libs/lambda-at-edge/tests/api-handler/api-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-handler.test.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-routes-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
- packages/libs/lambda-at-edge/tests/utils/runRedirectTest.ts
Continues redirects support from API routes (i.e API route is a source). RFC: https://github.com/serverless-nextjs/serverless-next.js/issues/587
Updated handler unit tests, e2e tests.
> feat(lambda-at-edge): support custom redirects from API routes

- package.json
This should publish alpha releases under alpha tag in npm, so the latest tag will only contain the stable releases. Will test on the next publish.
Ref: https://www.npmjs.com/package/@lerna/publish#--dist-tag-tag
> chore: publish prereleases to npm under alpha tag

- README.md
This would help users understand all currently supported features.
> docs: be more specific about supported features

- packages/serverless-components/domain/utils.js
I missed this in ea180e67515ee5dceed1c3e19731291615a7cbbb, where the domain alias being added to the distribution would overwrite aliases that were added when we create the distribution. Append the domain alias(es) to the list instead of creating a new Aliases.Items to preserve those.
There don't seem to be any tests for this component, so I manually verified running the built component locally. If I overlooked a test suite that should be updated, let me know.
> fix(serverless-component): when adding primary domain name to CloudFront distribution aliases, don't replace other aliases

- packages/e2e-tests/next-app/cypress/integration/headers.test.ts
- packages/e2e-tests/next-app/next.config.js
- packages/libs/lambda-at-edge/src/api-handler.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/src/headers/addHeaders.ts
- packages/libs/lambda-at-edge/src/routing/redirector.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-basepath-routes-manifest.json
- packages/libs/lambda-at-edge/tests/api-handler/api-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-handler.test.ts
- packages/libs/lambda-at-edge/tests/api-handler/api-routes-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-basepath-routes-manifest-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-basepath-routes-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-routes-manifest-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-routes-manifest.json
- packages/libs/lambda-at-edge/types.d.ts
This continues: https://github.com/serverless-nextjs/serverless-next.js/issues/587
* Supports custom headers on pages and API handlers
Caveats: because of the way the default handler is currently architected (using S3 origin + origin response), any path that hits the S3 origin has its `request.uri` rewritten to the S3 path. This includes SSG pages, SSG data requests, public files, etc. Because of this, to have a custom header on these paths, you will need to specify the S3 key rather than the path. This is different from Next.js.
For example: if you have an SSG page at path `/my-page`, you will need to specify the S3 key as the header source in `next.config.js`, which will probably be something like `/my-page.html`.
Also, you can't add headers to `next/static/*` or `static/*` paths, as …
> feat(lambda-at-edge): support custom headers (with caveats)

- packages/libs/lambda-at-edge/src/build.ts
Due to trailing slash redirects not removed from routesManifest, when trailingSlash: true is enabled, the API could get stuck in a redirect loop. We will manually implement trailing slash redirects for API routes.
> fix(lambda-at-edge): fix possible redirect loop in API handler

- packages/libs/lambda-at-edge/src/default-handler.ts
This fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/673 and https://github.com/serverless-nextjs/serverless-next.js/issues/646
* During `S3Check` block, when there's a dynamic route at root page level that uses  fallback via `getStaticPaths`, during S3 file serving, it was interfering with public files by overriding the `request.uri` with `.html` first, then in the branch for public files, it tries to serve an incorrect file. For example, `example.png` would be served with URI such as `example.png.html` due to this.
* The fix is to use make these branches exclusive and put public files branch at the top, so they will always get served correctly.
Existing tests pass. Tested with local serverless deployment. Will run e2e tests in CI and add new ones in another PR.
> fix(lambda-at-edge): fix dynamic routes with getStaticPaths interfering with public files

- packages/e2e-tests/next-app-dynamic-routes/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-dynamic-routes/pages/nested/[dynamic].tsx
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-origin-response.test.ts
Fixes/closes: https://github.com/serverless-nextjs/serverless-next.js/issues/673
Also adds proper `cache-control` header so that CloudFront can cache the responses including the 404 page.
> feat(lambda-at-edge): support fallback: false for getStaticPaths and fix cache-control header

- packages/e2e-tests/next-app-dynamic-routes/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-dynamic-routes/pages/index.tsx
- packages/libs/lambda-at-edge/src/default-handler.ts
* When fallback pages for dynamic routes are used, it shouldn't interfere with SSG and SSR pages - those should take precedence as defined here: https://nextjs.org/docs/routing/dynamic-routes#caveats
Added e2e tests to ensure this doesn't break.
> fix(lambda-at-edge): non-dynamic pages (SSG, SSR) should be prioritized over dynamic fallback pages

- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
This adds support for a new input, `deploy` that allows users to skip the deployment step (creating AWS resources). All build outputs will be stored in `.serverless_nextjs` folder - `default-lambda`, `api-lambda`, and `assets` (in same structure as accessed by the handler in s3).
This will give more flexibility to users who may wish to deploy using their own scripts, other IaC (e.g Terraform), etc. User is responsible for uploading all files to S3 themselves (with correct headers) and Lambdas.
This will close: https://github.com/serverless-nextjs/serverless-next.js/issues/642 and https://github.com/serverless-nextjs/serverless-next.js/issues/419
Added a unit test.
> feat(nextjs-component): add deploy input which can be set to false to skip deployment

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
* When preview mode was enabled these HTML pages with no props were trying to be rendered via SSR but they don't exist in `ssr.nonDynamic` object in the build manifest. Hence the router was returning `pages/404.html` and then the handler was trying to require this, leading to a 503.
I don't have e2e tests for preview mode but we can add it in the near future.
> fix(lambda-at-edge): serve HTML pages with no props (i.e static pages) properly on preview mode enabled

- packages/libs/lambda-at-edge/src/default-handler.ts
It can conflict if the app defines a rewrite from `/:path`
> fix(lambda-at-edge): don't rewrite data requests

- packages/libs/lambda-at-edge/package.json
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/yarn.lock
Updates s3-client v3 and adds retries to fix: https://github.com/aws/aws-sdk-js-v3/issues/1196
> fix(lambda-at-edge): add retries for s3 calls

- packages/serverless-components/domain/serverless.js
- packages/serverless-components/domain/utils.js
- packages/serverless-components/nextjs-component/.d.ts
* Also adds better logging during debug mode
* Should hopefully fix: https://github.com/serverless-nextjs/serverless-next.js/issues/722
> fix(domain, nextjs-component): set aliases correctly with domainType of apex and domain starting with www

- README.md
- packages/serverless-components/aws-cloudfront/__tests__/general-options.test.js
- packages/serverless-components/aws-cloudfront/lib/index.js
- packages/serverless-components/aws-cloudfront/serverless.js
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/188
Added unit tests, also tested manually.
> feat(aws-cloudfront, nextjs-component): support setting geo restrictions

- README.md
- packages/serverless-components/aws-cloudfront/__tests__/general-options.test.js
- packages/serverless-components/aws-cloudfront/lib/index.js
- packages/serverless-components/aws-cloudfront/serverless.js
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
There is `certificateArn` input, however it is tied to domain component: https://github.com/serverless-nextjs/serverless-next.js/search?q=certificatearn and also is less configurable.
This creates a more configurable input that's tied to the distribution but without needing to use the `domain` input (e.g if domains and certs are managed outside of this serverless component). It is especially useful in combination with the `aliases` input.
Added unit tests, but I will also test on my own app.
> feat(aws-cloudfront, nextjs-component): support setting certificate input in cloudfront

- packages/serverless-components/domain/utils.js
* When domain is used, it should completely manage all aliases attached to CloudFront distribution instead of trying to push onto existing aliases set. Otherwise, there could be strange behavior when it's manually updated and/or domains are changed.
* `aliases` input in `cloudfront` can be used if additional aliases apart from domain name are needed (and domain likely should be managed externally instead, as this is a more complex use case).
> fix(aws-cloudfront, nextjs-component): fix aliases updating when domain is used

- packages/libs/lambda-at-edge/src/api-handler.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/src/routing/rewriter.ts
- packages/libs/lambda-at-edge/tests/routing/rewriter.test.ts
- packages/libs/lambda-at-edge/types.d.ts
Should fix: https://github.com/serverless-nextjs/serverless-next.js/issues/733
> feat(lambda-at-edge): no-op rewrite support

- README.md
I'm fairly new to next.js and was only aware of this approach of loading environment variables:
https://nextjs.org/docs/basic-features/environment-variables
I could not make it work with this servlerss-next.js as it seems that the only way to forward env vars is via the `next.config.js`. It took me way too long to find out. (Especially as `.env.local`/`.env.production` did work as expected). So I've decided to add this FAQ section.
> README: clarify how to use `build.env`

- packages/libs/lambda-at-edge/src/default-handler.ts
Related issue: #776 
Examining how NextJS handle this, they return false in a catch after signing failure.
https://github.com/vercel/next.js/blob/a5cb28d907ad34865085d38d008130aaa4667427/packages/next/next-server/server/api-utils.ts#L350-L359
Instead of returning 403 for requests which contain both cookies, but which are invalid, a normal response object should be returned.
> Validate Existance of Cookies for Preview Mode - Default preview mode False

- packages/e2e-tests/next-app/pages/image-component.tsx
Just adds a simple page for the new Image component: https://github.com/serverless-nextjs/serverless-next.js/issues/725. Not tested yet - still need to port the image optimizer code into this component.
> test: add image component page to next-app e2e test

- packages/serverless-components/aws-cloudfront/__tests__/existing-distribution.test.js
- packages/serverless-components/aws-cloudfront/lib/index.js
- packages/serverless-components/aws-cloudfront/test-utils.js
Work to close #805 
Due to the way that CacheBehaviors are managed we needed to persist those for origins not controlled by serverless.
Tests have been written and tested locally in our next project, but didn't run the e2e tests.
> Add ability to persist cache behaviors not set in serverless

- packages/libs/lambda-at-edge/package.json
When installing `lambda-at-edge` independently and running the example code
```
const path = require('path');
const { Builder } = require("@sls-next/lambda-at-edge");
const nextConfigDir = __dirname;
const outputDir = path.join(nextConfigDir, ".serverless_nextjs");
const builder = new Builder(
nextConfigDir,
outputDir,
{
cmd: './node_modules/.bin/next',
cwd: process.cwd(),
env: {},
args: ['build']
}
);
(async () => await builder.build())();
```
I get the following error:
```
node build.js
node:internal/modules/cjs/loader:903
throw err;
^
Error: Cannot find module 'klaw'
```
Installing `klaw` via npm / yarn fixes it.
> klaw seems to be a dependency for "lambda-at-edge"

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
URL-decode request path before checking for public file in `manifest.json`. Prevent 404 responses when filename contains encoded characters.
Another unit test for public directory serving is added to verify functionality.
Fixes #822
> Fix not found for public files with encoded characters in path

- README.md
- packages/serverless-components/aws-lambda/serverless.js
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
Allows to specify ARN of existing role instead of creating a new one.
```yml
myNextApplication:
component: "@sls-next/serverless-component@{version_here}"
inputs:
roleArn: "arn:aws:iam::123456789012:role/MyCustomLambdaRole"
```
> Add inputs.roleArn for existing lambda role

- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
Currently, declared on README.md page `certificateArn` does not passed to `domain` component, resulting in searching for domain certificate, which works bad for subdomains, i.e. app.example.com
See issue here: https://github.com/serverless-nextjs/serverless-next.js/issues/821
> Pass certificateArn to domain component

- packages/libs/lambda-at-edge/src/api-handler.ts
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/src/headers/addHeaders.ts
- packages/libs/lambda-at-edge/src/image-handler.ts
- packages/libs/lambda-at-edge/src/images/imageConfig.ts
- packages/libs/lambda-at-edge/src/images/imageOptimizer.ts
- packages/libs/lambda-at-edge/src/index.ts
- packages/libs/lambda-at-edge/src/routing/redirector.ts
- packages/libs/lambda-at-edge/src/routing/rewriter.ts
- packages/libs/lambda-at-edge/src/types.ts
- packages/libs/lambda-at-edge/tests/build/build-no-api.test.ts
- packages/libs/lambda-at-edge/tests/build/build.test.ts
- packages/libs/lambda-at-edge/tests/dynamic-routes-precedence/dynamic-routes-precedence.build.test.ts
- packages/libs/lambda-at-edge/tests/integration/with-trailing-slash-next-config/with-trailing-slash-next-config.test.ts
- packages/libs/lambda-at-edge/tests/public-and-static-dir/public-and-static-dir.test.ts
- packages/libs/lambda-at-edge/tests/routing/redirector.test.ts
- packages/libs/lambda-at-edge/tests/routing/rewriter.test.ts
- packages/libs/lambda-at-edge/tests/test-utils.ts
- packages/serverless-components/nextjs-component/src/component.ts
>closes: #860 
This PR will ensure that the types used in the `@sls-next/lambda-at-edge` are included in the distribution.
- Move the `types.d.ts` into `src/types.ts`
- Export all types from `src/types.ts` in `src/index.ts`
This means the types that have cross package uses are accessible from the root e.g:
```ts
import type { RoutesManifest } from '@sls-next/lambda-at-edge'
```
> Update type declarations to be included in `dist` and exported at the root

- documentation/docs/cdkconstruct.md
Some background in @ibrahimcesar's comment [here](https://github.com/serverless-nextjs/serverless-next.js/pull/878#issuecomment-787217436).
When running the builder with the defaults, e.g. `new Builder('.', './build').build()` the process will hang as the builder just runs `next` with no args, which in-turn starts the next dev server. Not sure whether this is intended or something has changed as I don't recall this behavior - high chance I've just forgotten. Either way, this PR just updates the docs to avoid confusion.
> docs: adds the build arg to Builder in CDK docs

- packages/libs/lambda-at-edge/src/build.ts
Fixes: #907
* Recent Next.js version has a key for each locale in the prerender manifest routes, so we don't need to build it manually anymore. Only if version <= 2 will it do so.
> fix(lambda-at-edge): handle prerender-manifest v3 locales properly

- .github/workflows/CI.yml
Due to some flakiness in yarn internal package installation, seems ubuntu-latest (ubuntu 20) may not be stable yet?
> chore: downgrade CI workflow to ubuntu-18

- .github/workflows/e2e-tests.yml
GH actions recently started using Ubuntu 20 which uses aws cli v2. Without setting region there may be problems, e.g: https://github.com/actions/virtual-environments/issues/2791
Setting region to fix this.
> chore: add AWS default region to e2e workflow

- .github/workflows/CI.yml
* 12.x workflow has more coverage and we only need to upload it once
> chore: upload code coverage on node 12.x workflow only

- documentation/docs/cdkconstruct.md
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
It's quite often the case that you need to access the underlying resources, for example, to update their roles or to read their configuration to pass into another resource. This PR exposes all created resources as properties on the construct. It also allows users to pass in custom S3 configuration.
> fixes: #943 give access to underlying resources and enable custom s3 props

- packages/serverless-components/nextjs-cdk-construct/package.json
- packages/serverless-components/nextjs-cdk-construct/yarn.lock
Having all CDK Construct listed as prod dependencies causes conflicts in versioning, moving to peer dependencies and dev dependencies are recommended, more deets on this issue [here](https://github.com/serverless-nextjs/serverless-next.js/issues/950).
> fixes #950: moves cdk construct dependencies to peers

- packages/libs/lambda-at-edge/src/routing/rewriter.ts
Next.js doesn't follow redirect during a rewrite, so we should be in sync with it.
Fixes https://github.com/serverless-nextjs/serverless-next.js/issues/929
> fix(lambda-at-edge): do not follow redirect in fetch during rewrite

- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/types.d.ts
As mentioned in the PR #779 , baseDir wasn't included for the component, so I've added it here.
Without it, I was unable to run the deployed web-app on the server
Scenario for how I used this:
- Using yarn workspaces and lerna
- The next.js-project is inside `<root>/packages/my-web-app`
- Dependencies are hoisted to `<root>/node_modules`, this includes next, serverless-next.js, @material-ui, et.c.
- The serverless.yml is located at `<root>/packages/my-web-app/serverless.yml`
**`serverless.yml`**:
```yml
"@my-company/my-web-app":
component: "../../node_modules/@sls-next/serverless-component"
inputs:
build:
baseDir: "../../"
useServerlessTraceTarget: true
```
The web-app is now successfully deployed and it's able to resolve its dependencies once again.
I tracked down the issue to [nft's …
> Add baseDir from #779 to component to facilitate usage in monorepos

- README.md
Hey,
While creating the AWS policy I found a small error in the README.
```
Invalid Action: The action s3:HeadBucket does not exist.
Did you mean s3:ListBucket? The API called HeadBucket authorizes against the IAM action s3:ListBucket
```
Here is the aws [doc](https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html) regarding `HeadBucket`.
> To use this operation, you must have permissions to perform the `s3:ListBucket` action. 
Thank you for this amazing project !
> fix(README): remove s3:HeadBucket permission

- packages/libs/lambda-at-edge/scripts/copy-sharp-modules.ts
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/979 - seems this directory was growing indefinitely with each publish from my machine without this fix, it was not caught in e2e tests since that doesn't deploy from a published package, but instead builds locally from scratch (so dist/sharp_node_modules would not exist on each CI run).
Will likely deprecate last few versions which may cause this issue (and unnecessarily use Lambda space)
> fix(lambda-at-edge): ensure dist/sharp_node_modules empty before copying

- packages/libs/s3-static-assets/src/lib/readDirectoryFiles.ts
Hopefully fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/932
It looks like if `directory` was not properly split out by separator, even using `path.posix.join` would not join properly. For example if directory is `C:\test`, then `path.posix.join("C:\test", "**/*")` would result in `C:\test/**/*`. So we need to first remove the separator (either windows or posix separator) before joining.
This will result in a join of `path.posix.join("C:", "test", "**", "*")` which results in `C:/test/**/*` correctly.
I haven't tested on windows due to not having a local machine to test, but tested based on simulating windows paths and `split(path.win32.sep)`, it seems this should work.
> fix(s3-static-assets): fix s3 directory read for fast-glob on windows

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath-origin-response.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath-with-locales.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath.test.ts
Fixes #990 
There were two issues: 
1. Page requests happened with `basePath` in `s3Origin.path` while data requests had it in `request.uri`, so `normalizeUri` broke with fallback pages.
2. Since `basePath` starts with `/` all the S3 operations from response handler broke when using basePath.
> Fix SSG fallback with basepath

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/src/routing/locale-utils.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest.json
1. Locale-specific 404 pages
2. If no 404 static page exists, return blank 404 response instead (should fix https://github.com/serverless-nextjs/serverless-next.js/issues/894)
TODO: need to add tests in another PR
> fix(lambda-at-edge): various 404 page fixes:

- packages/serverless-components/nextjs-cdk-construct/__tests__/construct.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
The problem: 
Not having possibility to use multiple domainNames in the app.
Case:
We are developing an app using this lib, and we want the possibility to have `www.` in our url.
Temporary solution: 
To solve this problem now, we manually updated cloudfront to accept the same url with `www.` on it and then created the route53 record for that.
Final solution: 
The lib having a way to do that by it self, so I changed the `domainName` prop to `domainNames` which is an array of strings ( Cloud front accept that ) and looped this array to create all the route53 records for the given domain list.
> feat: adding support for multiple domainNames

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
The problem:
My last pull request, https://github.com/serverless-nextjs/serverless-next.js/pull/1009, for adding support for multiple domains in the app, has a problem that I missed to handle.
When creating more than one Domain nome for the app, it loops through the domain name list and create one Route53 Record for each, the problem is that I forgot to make it generate different id's for each item of the list, so when we have more than one item it's going to fail the deploy with the fowling error:
```
Error: There is already a Construct with name 'AliasRecord' in NextJSLambdaEdge [AppName]
at Node.addChild (.../node_modules/constructs/src/construct.ts:534:13)
at new Node (.../node_modules/constructs/src/construct.ts:75:22)
at new ConstructNode …
```
> fix: unique construct id for each domain name

- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/tests/build/build-no-api.test.ts
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-no-api/.next/images-manifest.json
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-no-api/next.config.js
With a non-default loader declaration there's no way to use the image lambda from image components, so no need to generate it. 
Would be nice to not need it if `next/image` isn't used, but it doesn't seem like there's a way to tell from the build artifacts.
> Images lambda is not needed with non-default loader

- packages/serverless-components/nextjs-cdk-construct/__tests__/construct.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
Rather than spreading over all props here https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-cdk-construct/src/index.ts#L250 `edgeLambdas` are concatenated to the default ones created in the construct.
closes #1014
> feat(sls-next/cdk-construct): edgeLambdas concatenated with default edge lambdas

- packages/e2e-tests/next-app-with-locales/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-with-locales/pages/fallback-blocking/[slug].tsx
- packages/libs/lambda-at-edge/src/default-handler.ts
Fixes a bug in #1007 – with fallback: blocking the page render function gets passed the S3 uri with .html which makes the backend router disagree with the front-end about the page path.
This complexity results from the split between request and response lambdas. If they are combined the request object can have the correct uri throughout.
> Fix router path in fallback SSG

- packages/libs/lambda-at-edge/package.json
- packages/libs/lambda-at-edge/rollup.config.js
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/src/s3-client.ts
- packages/libs/lambda-at-edge/tests/build/build-dynamic.test.ts
- packages/libs/lambda-at-edge/tests/build/build-no-api.test.ts
- packages/libs/lambda-at-edge/tests/build/build-with-locales.test.ts
- packages/libs/lambda-at-edge/tests/build/build.test.ts
- packages/libs/lambda-at-edge/yarn.lock
Note: testing rollup config to properly bundle dynamic imports like s3client which is not always needed. The cost is an additional wrapper on top of main code but this seems expected optimization from Rollup.js (preloading and parsing optimization). 
Previously, inlining dynamic imports into one file was still causing that code to be at least partially preloaded outside of the handler, e.g initializing some S3/AWS SDK related objects even if the S3Client itself was only initialized when needed. So it caused higher cold starts due to this for all paths. With this change, we split into multiple chunks. Total there should be a few chunks:
* Entry chunk (wrapper of ~20 lines on top of other code)
* Core chunk (all of the routing code bundled into one file)
* Dynamic chunks (e.g S3 client, …
> perf(lambda-at-edge): fix rollup bundling for dynamic imports perf

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
Passing `defaultBehavior.edgeLambdas` was being applied to `defaultBehavior` and  to `_next/data/*` behaviour. Could cause unintended side effects.
> fix(sls-next/cdk-construct): defaultBehavior.edgeLambdas only applied to defaultBehavior

- packages/libs/lambda-at-edge/package.json
- packages/libs/lambda-at-edge/rollup.config.js
- packages/libs/lambda-at-edge/yarn.lock
Since #1029 rebuilding locally keeps accumulating rollup modules, making local builds difficult to deploy.
Each time you run `yarn` in root or under lambda-at-edge a new set of modules is created. They all get included in any builds that link to the local repository, like e2e-tests.
Not sure this is the best solution, but AFAICT rollup itself doesn't have an option to clean up the build directory.
> Delete old files from dist on build

- packages/serverless-components/nextjs-cdk-construct/__tests__/construct.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
Allow the user to leave `hostedZone` undefined. In this case the A record will not be created, but the CloudFront distribution will be configured with the domain name + certificate.
Fixes #1027.
> feat(cdk-construct): Support for outside hosted domain

- packages/libs/core/src/locale.ts
- packages/libs/core/tests/locale.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-locales.test.ts
This allows matching a user's language settings even if the first preference does not match the locales available.
E.g. someone whose browser is set to prefer German, but accept French, can be served a French version after this change if German is not an option.
> Extend locale matching to secondary languages

- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/tests/build/build-dynamic.test.ts
- packages/libs/lambda-at-edge/tests/build/build-no-api.test.ts
- packages/libs/lambda-at-edge/tests/build/dynamic-app-fixture/.next/export-marker.json
The past couple of versions of Next.js have an indication of whether the image component is imported in .next/export-marker.json so use it to avoid building image handler when not used.
Should prevent issues like #1030 for people upgrading with a restricted role.
> Check if image component is used

- .github/workflows/e2e-tests.yml
- packages/e2e-tests/next-app-with-locales/cypress/integration/pages.test.ts
Moves building packages and utils for e2e tests out of the matrix into the initialize step. This reduces the chance of failures due to one or more of the builds failing.
This may make it slower to run e2e tests (when there's no queue) because stashing the build takes an extra minute or so.
> Build and stash packages only once in e2e tests

- packages/libs/lambda-at-edge/tests/utils/triggerStaticRegeneration.test.ts
These were actually failing but because the Promise was not awaited, it did not fail the tests. Probably need to add some eslint rules to prevent this
> test(lambda-at-edge): fix up regeneration tests silent failures due to not await-ing

- packages/e2e-tests/next-app-dynamic-routes/package.json
- packages/e2e-tests/next-app-dynamic-routes/yarn.lock
- packages/e2e-tests/next-app-using-serverless-trace/package.json
- packages/e2e-tests/next-app-using-serverless-trace/yarn.lock
- packages/e2e-tests/next-app-with-base-path/package.json
- packages/e2e-tests/next-app-with-base-path/yarn.lock
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/package.json
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/yarn.lock
- packages/e2e-tests/next-app-with-locales/package.json
- packages/e2e-tests/next-app-with-locales/yarn.lock
- packages/e2e-tests/next-app-with-trailing-slash/package.json
- packages/e2e-tests/next-app-with-trailing-slash/yarn.lock
- packages/e2e-tests/next-app/package.json
- packages/e2e-tests/next-app/yarn.lock
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/tests/build/build.test.ts
This is two changes:
1. Copy chunks folder contents into the api/default lambdas. It seems this is generated in newer versions (e.g 10.0.6 and above at least) so we should copy it if present.
2. Update e2e tests to latest 10.2.2.
Going forward, it may be better to drop the previous tests since it makes the codebase less maintainable (have to maintain backwards compatibility) due to Next.js's various model changes (e.g for locales). Also no point doing the version range since they will be locked in the lockfile, we can manually update this as needed when newer Next.js versions come out.
> fix(lambda-at-edge): copy js chunks from .next/serverless/chunks to api/default lambdas if present

- packages/libs/lambda-at-edge/src/build.ts
Tests may still be flakey for ISR, not sure, however, I noticed they were failing legitimately due to the `chunks` not being copied into the lambda dir.
> fix: also copy chunks for the revalidate lambda

- packages/libs/core/package.json
- packages/libs/core/yarn.lock
These are used in core so should be added to its package.json to avoid dependency resolution issues (although it's in lambda-at-edge so has been working for the most part)
> chore(core): add cookie and path-to-regexp as dependencies

- .github/workflows/e2e-tests.yml
- package.json
Based on testing locally, it seems the exit code is lost in the `|| true` in postinstall which I think is meant to make `opencollective-postinstall` non-erroring.
> Try to fix build step return code for CI

- packages/e2e-tests/next-app-with-locales/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-locales/next.config.js
- packages/e2e-tests/next-app-with-locales/pages/dynamic-ssr/[slug].tsx
- packages/libs/core/src/handle/default.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-locales.test.ts
Fixes #1131
Next.js routing requirements are pretty odd here. It needs the "original" url (before rewrites) to support asPath, but cannot cope with locales.
SSG routes (fallback or ISR) already get the locale added for fetching the static page.
> Fix locale rewrites to dynamic ssr

- packages/libs/core/src/build/index.ts
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/tests/build/build-dynamic.test.ts
- packages/libs/lambda-at-edge/tests/build/build-with-locales.test.ts
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-with-locales/.next/prerender-manifest.json
- packages/libs/lambda-at-edge/tests/build/simple-app-fixture-with-locales/.next/serverless/pages-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-locales-with-trailing-slash.json
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-with-locales.json
- packages/libs/lambda-at-edge/tests/regeneration-handler/default-build-manifest-with-locales.json
Uses build manifest for asset build step, instead of duplicating locale logic using page and prerender manifests.
Also drops unnecessary (unlocalized) and wrong (double localized) paths from the manifest now that all the routing logic uses locale uris.
> Refactor locale build

- package.json
Coverage takes ages if e2e tests have been built. This drops `yarn test` from several minutes to <45s for me. `yarn jest` running in parallel takes less than 25s now.
> Skip creating coverage for untested e2e test files

- packages/serverless-components/aws-sqs/__tests__/deploy.test.js
- packages/serverless-components/aws-sqs/serverless.js
- yarn.lock
Initial issue: https://github.com/serverless-nextjs/serverless-next.js/issues/1098#issuecomment-852075948
> fix: only delete the sqs queue if it already exists in the state

- packages/serverless-components/aws-sqs/package.json
- packages/serverless-components/aws-sqs/utils.js
- packages/serverless-components/nextjs-component/package.json
- packages/serverless-components/nextjs-component/src/component.ts
- packages/serverless-components/nextjs-component/yarn.lock
Make use of the recently GA [high throughput mode](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-sqs-now-supports-a-high-throughput-mode-for-fifo-queues/) for FIFO queues.
Relatively big bump in aws-sdk versions, hopefully nothing breaks. I tried making the CDK change, but it seems even upgrading the libraries to latest would not yet support these parameters.
This is pretty niche, but shouldn't hurt anything even if you don't actually come close to the limits.
> Use high throughput mode for regeneration SQS

- packages/libs/core/src/handle/default.ts
- packages/libs/core/src/handle/error.ts
- packages/libs/core/src/handle/fallback.ts
- packages/libs/core/src/route/data.ts
- packages/libs/core/src/route/notfound.ts
- packages/libs/core/src/route/page.ts
- packages/libs/core/src/types.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-locales.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler.test.ts
Fixes the status code of normal static pages ending /404 or /500 (e.g. dynamic SSG page id).
Also adds tests for the different cases.
> Set error status codes in core, refactor error handling

- .github/workflows/CI.yml
* Will speed up CI process, doesn't really matter if e2e fails because of compile/unit test error, but this will make it faster to run things.
> chore: start e2e-tests simultaneously instead of waiting on build

- packages/serverless-components/nextjs-cdk-construct/__tests__/utils.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/utils/readInvalidationPathsFromManifest.ts
Dynamic route segments start with a colon in some versions/manifests and
with a square bracket in others. This change ensures both are recognized
correctly.
> Match dynamic route segments with square bracket

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
This makes it possible to specify e.g. the price class used.
> Support override props for CloudFront distribution

- packages/e2e-tests/next-app-dynamic-routes/cypress.json
- packages/e2e-tests/next-app-using-serverless-trace/cypress.json
- packages/e2e-tests/next-app-windows/cypress.json
- packages/e2e-tests/next-app-with-base-path/cypress.json
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress.json
- packages/e2e-tests/next-app-with-locales/cypress.json
- packages/e2e-tests/next-app-with-trailing-slash/cypress.json
- packages/e2e-tests/next-app/cypress.json
- packages/e2e-tests/prev-next-app-dynamic-routes/cypress.json
- packages/e2e-tests/prev-next-app-with-base-path/cypress.json
- packages/e2e-tests/prev-next-app-with-trailing-slash/cypress.json
- packages/e2e-tests/prev-next-app/cypress.json
They aren't used at the moment really (and will take a long time to upload) so disabling it for now.
> chore(e2e-tests): update cypress.json to disable videos

- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/__tests__/initialize.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
Trying to increase # max retries to 10 which should hopefully alleviate some throttling issues by retrying for longer (up to 200ms * 2^10 or around 100 seconds)
> fix: tweak aws retry policy

- packages/libs/lambda-at-edge/tests/integration/no-next-config/no-next-config.test.ts
This test has started timing out, with uncached next builds becoming slower in newer versions.
Remove the timeout setting, since global integration test timeout is 35s.
E.g. https://github.com/serverless-nextjs/serverless-next.js/pull/1258/checks?check_run_id=2863612447#step:6:16
> Remove shorter no-next-config timeout

- packages/e2e-tests/next-app-with-locales/cypress/integration/data-requests.test.ts
- packages/e2e-tests/next-app-with-locales/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-with-locales/pages/ssr-page-2.tsx
- packages/libs/core/src/handle/default.ts
The default locale addition in #1132 did not take data routes into account and adds the locale in the wrong part of the uri.
Data routes always have a locale when requested by Next.js so that workaround isn't needed.
This should fix #1267
> Test for and fix data route locales

- packages/e2e-tests/next-app/cypress/integration/data-requests.test.ts
- packages/e2e-tests/next-app/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app/pages/index.tsx
- packages/e2e-tests/next-app/pages/ssr-page-2.tsx
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-origin-response.test.ts
As a result, for static pages, in the origin response handler the route is wrong and it cannot find a route for "/index" and it leads to setting a status code of 404.
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/1277
> fix(lambda-at-edge): fix reconstruction of uri for "index.html" -> "/" instead of "/index" in origin response handler

- README.md
- packages/libs/cloudfront/src/index.ts
- packages/libs/cloudfront/src/lib/cloudfront.ts
- packages/libs/cloudfront/tests/aws-sdk.mock.ts
- packages/libs/cloudfront/tests/cache-invalidation.test.ts
- packages/libs/cloudfront/tests/check-cf-distribution-ready.test.ts
- packages/serverless-components/nextjs-component/__mocks__/@sls-next/cloudfront.js
- packages/serverless-components/nextjs-component/__tests__/basepath.test.ts
- packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts
- packages/serverless-components/nextjs-component/__tests__/deploy.test.ts
- packages/serverless-components/nextjs-component/src/component.ts
This is needed as the CF distribution may not be ready when invalidations happen. Thus if  someone accesses the page after invalidations are complete but before CF distribution is ready, it may cause an old page to be cached.
Also added a CloudFront boolean input `cloudfront.waitBeforeInvalidate` which can be used to configure wait for the distribution to be ready before proceeding with invalidations (default true, can be disabled)
> fix(nextjs-component, cloudfront): wait for distribution to be ready before creating invalidations.

- packages/e2e-tests/test-utils/scripts/run-e2e-ci.ts
* Now that there is a longer retry policy, it may not be necessary anymore?
> chore(e2e-tests): comment out random sleep for e2e tests

- packages/e2e-tests/next-app/cypress/integration/static-regeneration.test.ts
- packages/e2e-tests/prev-next-app/cypress/integration/static-regeneration.test.ts
- packages/libs/core/src/route/page.ts
Fixes prerendered dynamic ISR broken in #1238
Also, makes the ISR tests retryable so that failures can be trusted.
> Fix ISR, make tests retryable

- packages/libs/core/src/build/index.ts
- packages/libs/core/src/handle/default.ts
- packages/libs/core/src/route/locale.ts
- packages/libs/core/src/types.ts
- packages/libs/core/tests/route/locale.test.ts
This implements basic domain locale detection now the `config.i18n.domains` section is respected.
I'm open for refactoring suggestions, as I'm not really deep in this project. Just wanted to get it in a pulll request, as I'm on vacation next week.
> feat: Add domain locale detection (#1283)

- packages/e2e-tests/test-utils/cypress/custom-commands.ts
- packages/libs/core/src/route/redirect.ts
- packages/libs/core/tests/route/redirect.test.ts
- packages/libs/lambda-at-edge/tests/utils/runRedirectTest.ts
* To be consistent with Next.js (see vercel.com redirection behavior)
> fix(core): add s-maxage=0 cache-control headers to redirect responses

- README.md
ISR is no longer alpha-only. Also, default runtime has changed and there's a fourth lambda function.
I do wonder about the image lambda: the readme says "Note that the sharp image library is built for NodeJS 12.x" – is that still true and does it mean the default for that should be reverted?
> Update README on lambda runtime and ISR

- .github/workflows/CI.yml
- package.json
- scripts/upload-handler-sizes.ts
- yarn.lock
This will help later to calculate handler size diffs in future PRs.
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1314
> chore: calculate and upload handler sizes to s3 on master builds

- packages/libs/lambda-at-edge/src/build.ts
* This wasn't working properly since `copyTraces()` was always copying to the default lambda directory. We need to pass in the directory.
* Won't add tests since serverless-trace is already getting deprecated as of later Next.js versions (e.g 10.2.3) but manually tested.
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1098
> fix(lambda-at-edge): properly copy node_modules in serverless-trace mode for regeneration lambda

- .github/workflows/CI.yml
- package.json
- scripts/comment-handler-sizes.ts
- scripts/handler-size-utils.ts
- scripts/upload-handler-sizes.ts
- yarn.lock
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1314. For fork/dependabot PRs it would need a bit additional work (i.e a locked down API to post the comment, etc.) and possibly doing some prettifying via a table, etc.
> chore: post handler size comparisons for non-fork PRs

- packages/e2e-tests/next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app/next.config.js
- packages/libs/core/src/route/page.ts
- packages/libs/core/src/route/rewrite.ts
- packages/libs/core/tests/route/rewrite.test.ts
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/1328
> fix(core): support no-op rewrites

- packages/e2e-tests/next-app-using-serverless-trace/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-using-serverless-trace/next.config.js
- packages/e2e-tests/next-app-windows/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-windows/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-windows/next.config.js
- packages/e2e-tests/next-app-with-base-path/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-base-path/next.config.js
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/next.config.js
- packages/e2e-tests/next-app-with-locales/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-locales/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-locales/next.config.js
- packages/e2e-tests/next-app-with-trailing-slash/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-trailing-slash/next.config.js
- packages/e2e-tests/next-app/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app/next.config.js
- packages/e2e-tests/prev-next-app-with-base-path/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app-with-base-path/next.config.js
- packages/e2e-tests/prev-next-app-with-trailing-slash/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app-with-trailing-slash/next.config.js
- packages/e2e-tests/prev-next-app/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/prev-next-app/next.config.js
* To avoid causing GH API throttling for actual GH Actions usage
> test(e2e-tests): update to a different external api

- packages/libs/lambda-at-edge/tests/image-handler/image-handler-with-basepath.test.ts
- packages/libs/lambda-at-edge/tests/image-handler/image-handler.test.ts
Sharing filenames with the non-basepath test meant these sometimes got served from cache.
Using `yarn jest` they could happen either order and the other would fail randomly.
This unshares the names and adds explicit tests for caching.
> Fix flaky image handler test

- packages/compat-layers/lambda-at-edge-compat/__tests__/next-aws-cloudfront.response.test.js
- packages/compat-layers/lambda-at-edge-compat/next-aws-cloudfront.js
- packages/e2e-tests/next-app-dynamic-routes/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-dynamic-routes/pages/optional-catch-all-ssg-with-fallback/[[...catch]].tsx
- packages/libs/core/src/build/index.ts
- packages/libs/core/src/handle/fallback.ts
- packages/libs/core/src/route/data.ts
- packages/libs/core/src/route/page.ts
- packages/libs/core/src/types.ts
- packages/libs/core/tests/handle/default.test.ts
- packages/libs/core/tests/handle/fallback.test.ts
- packages/libs/core/tests/route/rewrite.test.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/build/build-dynamic.test.ts
- packages/libs/lambda-at-edge/tests/build/build-no-api.test.ts
- packages/libs/lambda-at-edge/tests/build/build-with-locales.test.ts
- packages/libs/lambda-at-edge/tests/build/dynamic-app-fixture/.next/prerender-manifest.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-origin-response.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath-origin-response.test.ts
Fixes #1286 and adds support for prerendered notFoundRoutes.
Does not cache notFound: true results in S3. It seems that next.js server does not cache them either.
> Not found support in SSG fallback

- packages/libs/lambda-at-edge/src/default-handler.ts
This is no longer needed for tests and makes no difference.
> Remove static request querystring hack

- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-build-manifest-origin-response.json
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-origin-response.test.ts
- packages/libs/lambda-at-edge/tests/default-handler/default-handler-with-basepath-origin-response.test.ts
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1277
Also removed the root catch-all in build manifest for all origin response tests so we can do a proper index page test that status code remains 200 (not 404).
> fix(lambda-at-edge): fix reconstruction of basepath index uri

- packages/e2e-tests/next-app-using-serverless-trace/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-using-serverless-trace/next.config.js
- packages/e2e-tests/next-app-windows/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-windows/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-windows/next.config.js
- packages/e2e-tests/next-app-with-base-path/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-base-path/next.config.js
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-locales-using-serverless-trace/next.config.js
- packages/e2e-tests/next-app-with-locales/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-locales/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-with-locales/next.config.js
- packages/e2e-tests/next-app-with-trailing-slash/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app-with-trailing-slash/next.config.js
- packages/e2e-tests/next-app/cypress/integration/redirects.test.ts
- packages/e2e-tests/next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app/next.config.js
- packages/e2e-tests/prev-next-app-with-base-path/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app-with-base-path/next.config.js
- packages/e2e-tests/prev-next-app-with-trailing-slash/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app-with-trailing-slash/next.config.js
- packages/e2e-tests/prev-next-app/cypress/integration/redirects.test.ts
- packages/e2e-tests/prev-next-app/cypress/integration/rewrites.test.ts
- packages/e2e-tests/prev-next-app/next.config.js
jsonplaceholder.typicode.com started adding Cloudflare browsers insights: https://support.cloudflare.com/hc/en-us/articles/360033929991-Cloudflare-Browser-Insights to the main page, which has a unique ID in the HTML source each time, so we can't use it anymore
> test(e2e-tests): fix external site used in e2e tests

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-component/src/component.ts
it adds the resource creation conditions that my suggestions for fix #1476. I think we need to create SQS and Regeneration Handler at deployment time, because it can 'fallback: true|blocking' with 'revaliate'.
I would like your review on whether that is an appropriate solution or not. thanks
> fix(nextjs-component, nextjs-cdk-construct): create AWS resources for dynamic SSG (#1476)

- packages/serverless-components/nextjs-component/src/component.ts
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/1486
> fix(nextjs-component): allow setting custom regeneration lambda name

- packages/e2e-tests/next-app-with-locales/cypress/integration/pages.test.ts
- packages/e2e-tests/next-app-with-locales/next.config.js
- packages/e2e-tests/next-app-with-locales/pages/index.tsx
- packages/e2e-tests/next-app-with-locales/pages/ssg-page.tsx
- packages/libs/core/src/route/locale.ts
- packages/libs/core/tests/route/locale.test.ts
Related: https://github.com/serverless-nextjs/serverless-next.js/issues/1478
> fix(core): allow lowercase locale prefixes

- .github/workflows/CI.yml
- .github/workflows/cleanup-e2e-tests.yml
- .github/workflows/e2e-tests.yml
- resolve #1239 
- Setup-node officially supports dependency caching the other day.  
(https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/)
It will improve CI workflow speed.
> Add cache to CI workflows

- packages/libs/lambda-at-edge/src/s3/s3StorePage.ts
For the root path `/` the `s3StorePage` was not correctly storing to the `index.html` file and instead was storing as `.html`
Added an extra regex `replace()` to deal with the root path. 
#1098
> Fix ISR issue with `index.ts`

- packages/libs/core/src/route/data.ts
- packages/libs/core/src/route/page.ts
When route was dynamic e.g. `/[[...slug]]` data and page routes would return the SSG content, rather than the SSR.
Added `&& !isPreview` to ensure it matches the same logic as non dynamic routes.
Fixes #1527
> Fix Preview Mode when a dynamic route is used

- packages/e2e-tests/next-app-with-locales/cypress/integration/static-regeneration.test.ts
- packages/e2e-tests/next-app-with-locales/next-env.d.ts
- packages/e2e-tests/next-app-with-locales/package.json
- packages/e2e-tests/next-app-with-locales/pages/revalidated-ssg-page.tsx
- packages/e2e-tests/next-app-with-locales/pages/revalidated-ssg-pages/[id].tsx
- packages/e2e-tests/next-app-with-locales/yarn.lock
- packages/libs/core/src/build/index.ts
- packages/libs/lambda-at-edge/tests/build/build-dynamic.test.ts
- packages/libs/lambda-at-edge/tests/build/build-with-locales.test.ts
* We need to add SSR dynamic pages for keys without the locale, as otherwise for default locale routes, they do not find an SSR page and does not trigger ISR (regeneration lambda)
Fixes: https://github.com/serverless-nextjs/serverless-next.js/issues/1598
> fix(lambda-at-edge, e2e-tests): fix and add e2e tests for ISR pages when locales are used

- packages/e2e-tests/next-app-experimental/cypress/integration/rewrites.test.ts
- packages/e2e-tests/next-app-experimental/next.config.js
- packages/libs/core/src/build/index.ts
- packages/libs/core/src/build/ssr.ts
- packages/libs/core/src/build/types.ts
- packages/libs/core/src/handle/default.ts
- packages/libs/core/src/route/page.ts
- packages/libs/core/src/types.ts
- packages/libs/lambda-at-edge/src/build.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
- packages/serverless-components/nextjs-component/src/component.ts
* experimental: set build.separateApiLambda = false to enable single lambda for pages + APIs
* moves API page routing/rendering to default handler routing, which is cleaner as it already provides abstractions over different route types. It's easier also to add logic in page manifest parsing to treat API pages as another page type, so it lives with the regular HTML/SSG/SSR pages. We can get rewrite logic mostly for free.
* cross rewrites like /page <-> /api/page should now work (there is a simple e2e test added for the basic cases).
* we will also get nice 404 pages instead of the previous text-only, uncustomizable 404 page for APIs.
* this is mainly only tested in e2e next-app-experimental. But if this becomes the default later, we will need to update unit tests
Fixes: …
> feat(core, nextjs-component): improve routing and support cross rewrites for consolidated API pages in default lambda

- documentation/docs/faq.md
The examples link was corrected in `README.md` in 468da0daf6c120e9888048bad0f3dc8e991f0a7c. This fixes it in `faq.md`.
> Update faq.md with fixed examples link

- README.md
missing comma in readme documentation for deployment permissions list
> doc: missing comma

- packages/libs/core/src/images/imageOptimizer.ts
- packages/libs/core/src/images/index.ts
- packages/libs/lambda-at-edge/src/image-handler.ts
- packages/libs/lambda/src/handlers/image-handler.ts
If Basepath is set, it needs to be removed from the query
Not normalised -> error 403
`url: '<base-path>/assets/images/logo.svg'`
Normalised -> 200
url: `'/assets/images/logo.svg'`
> Add URL normalise to image optimiser URL

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
- packages/serverless-components/nextjs-cdk-construct/src/utils/toLambdaOption.ts
fixes issue #2048  
The regeneration function was the only function where the runtime could not be modified through setttings prop
This can cause the regeneration lambda function to time out an fail
The pull request adds the option to configure the regeneration runtime (memory, timeout, role, and node version)
as a note I have not modified the nomenclature for this function but it is the only lambda handler that is named as Function instead of Lambda for the others (nextApiLambda, nextDefaultLambda, nextImageLambda) but the regeneration lambda is named RegenerationFunction. I can modify that also if needed.
> feat(nextjs-cdk-construct): add runtime options to regeneration

- packages/libs/core/src/images/sendEtagResponse.ts
- packages/libs/core/tests/images/imageOptimizer.test.ts
This PR fixed about invalid ETag value.
ETag header value should begins double quote character (`"`)  or `W/`, referring to MDN docs.
PR also fixed that CloudFront will remove the ETag header when compressing files; because CloudFront also converts ETag header value, but it is missing double quote character.
References:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#directives
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-etag-header
> fix(libs): resolve invalid syntax on etag

- packages/libs/core/src/build/types.ts
- packages/libs/core/src/images/imageConfig.ts
- packages/libs/core/src/images/imageOptimizer.ts
- packages/libs/core/tests/images/image-images-manifest.json
- packages/serverless-components/nextjs-cdk-construct/src/utils/toLambdaOption.ts
Thanks so much for this awesome package! This request aims to make the new formats setting from next.config in next 12 (https://nextjs.org/docs/api-reference/next/image#acceptable-formats) work as expected and allow opt-in or out for avif optimization (the default being, as next's is, webp).
closes #2235
> Allow opt-in for AVIF optimization

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
I ran into the problem described in #1620: when using a `basePath` in the Next.js application, the S3 asset bucket remains empty. There was a fix mentioned in the issue, but no PR yet, so I've taken the liberty to make that change and open this PR. I tried the change locally and it worked.
@dphang or any other maintainer: I'm of course willing to add tests, but I couldn't figure out how to integrate such a basePath test with the existing CDK tests.
> Use basepath in s3 assets

- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/cache-behavior-options.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/custom-url-origin.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/lambda-at-edge.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/origin-with-custom-headers.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/origin-with-custom-origin-config.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/origin-with-path-pattern.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/__snapshots__/s3-origin.test.ts.snap
- packages/serverless-components/aws-cloudfront/__tests__/cache-behavior-options.test.ts
- packages/serverless-components/aws-cloudfront/src/getCacheBehavior.ts
- packages/serverless-components/aws-cloudfront/src/getDefaultCacheBehavior.ts
I have added the ability to set the ResponseHeadersPolicyId on the Cloudfront behaviours.
I had to update some snapshots to get the tests to pass, though I get failures when Jest gets to the `Running coverage on untested files...` section.
I haven't had a chance to run an end-to-end test with it yet though.
> feat(cloudfront): add ability to set ResponseHeadersPolicyId

- packages/libs/core/src/images/imageOptimizer.ts
Fixes #2272 
Change maintains the upstream `Cache-Control` if present in the upstream response. rather than overiding it with the default.
> Use existing upstream `Cache-Control` if present on upstream response

- documentation/docs/cdkconstruct.md
- packages/serverless-components/nextjs-cdk-construct/__tests__/construct.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
Hello, first of all thanks for this great library, and thanks for porting it to CDK.
Currently, I'm working on a Cloudfront app that has the domain as `*.mypage.com`
Where `*` is a brand selected by our customers, identifying it has become difficult for a couple of reasons:
- I don't know how to access the original event sent to the lambda (I also don't know how I can implement this one) so I went to the 2nd option which is reading the `Host` header.
- When reading the `Host` header on SSR, it works quite well, except when the request is to `_next/data`, in that case, the `Host` header is from CloudFront because it's not being forwarded, this PR adds the ability to forward headers.
I've tried to keep it up with what was needed, it was being tested by my end and I added a unit test, please …
> CDK: Allow to whitelist headers

- packages/libs/core/src/handle/api.ts
- packages/libs/core/tests/handle/api.test.ts
this fixies #2327.
This bug is caused by [next.js PR #32999](https://github.com/vercel/next.js/pull/32999/files#diff-527588a4dadf6d2d9111766e571eec95cd658fea219da01bb7f259a6c0a70d6aR17-R25) (included in next v12.0.9).
I implemented the getter function of event.req & event.res.
Or should I update next.js v11.1.2 to v12 in packages/libs/core/package.json?
> getter function for http base class in api handler

- documentation/docs/cdkconstruct.md
- packages/serverless-components/nextjs-cdk-construct/__tests__/construct.test.ts
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
Our company has started to extensively use the CDK construct for next.js and it's been working great so far 🎉
However, since each app builds its own 3 unique cache policies, we have started to run into a limitation. AWS only allows you to have 20 cache policies per account. See `Cache policies per AWS account` in AWS docs here:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-policies
Since all the next apps have the same 3 cache policies duplicated, we created 3 universal ones to share across all our apps. Then, we will simply import the shared 3 policies into our next apps.
EX:
```
nextStaticsCachePolicy: CachePolicy.fromCachePolicyId(
scope,
'NextImageCache',
'unique-cache-policy-id-here'
)
```
This PR allows you to pass those policies …
> feat(nextjs-cdk-construct): Allow cache policies to be provided as props

- packages/libs/core/src/handle/default.ts
- packages/libs/core/tests/handle/default.test.ts
This fixies #2327.
The reason for this bug is the same as for #2344.
When `useV2Handler: true` set in `serverless.yml`, this problem was not solved.
I Implemented getter function in default handler.
> add getter to event req & res object in default handler.

- packages/libs/lambda-at-edge/src/regeneration-handler.ts
Fix the regex to only replace `.js` at the end of the string
Fixes #2349
> Fix: wrong replace causing "on" files on S3

- packages/libs/core/src/handle/redirect.ts
- packages/libs/lambda-at-edge/src/default-handler.ts
This fixes #2346.
Added redirect to getStaticProps as shown in the code below.
```tsx
import type { NextPage, GetStaticProps } from "next";
import { useRouter } from "next/router";
export const getStaticProps: GetStaticProps = async () => {
const data = await fetch("https://github.com/serverless-nextjs/serverless-next.js").then((res) =>
res.text()
);
if (data.length > 0) {
return {
redirect: {
permanent: false,
destination: "/bar",
},
};
}
return {
props: {},
};
};
export async function getStaticPaths() {
return {
paths: [],
fallback: true,
};
}
const Foo: NextPage = () => {
const router = useRouter();
const { id } = router.query;
return <p>Post: {id}</p>;
};
export default Foo;
```
And I deployed it to vercel, and the following response was returned.
```
Request URL: …
```
> fix redirect in getStaticProps

- packages/e2e-tests/next-app-with-locales/cypress/integration/static-regeneration.test.ts
- packages/libs/core/src/handle/redirect.ts
I fixed the e2e test code that my PR (#2393) caused to break.
@dphang 
Sorry, I fixed broken e2e test code.
Please review.
> Fix e2e static regeneration test code

- packages/serverless-components/nextjs-cdk-construct/src/index.ts
- packages/serverless-components/nextjs-cdk-construct/src/props.ts
When using `Builder` from `@sls-next/lambda-at-edge` there's a really useful functionality to add an extra handler (in case you want to call `callbackWaitsForEmptyEventLoop = false`, set any tracer or establish a DB connection, really useful!).
But unfortunately it's kinda useless on CDK because the default handler is stuck at `index.handler`, this PR solves that, so you can do the following:
```ts
export function MyStack(scope: Construct, id: string, props?: cdk.StackProps) {
/** other things */
new NextJSLambdaEdge(stack, `${id}-next`, {
memory: 1536,
runtime: Runtime.NODEJS_14_X,
handler: 'handler.handler' // <------ We could replace the default handler and make use of the one we provided to "build"
})
}
const builder = new Builder('.', './build', {
args: ['build'], 
handler: …
```
> Allow to set custom handler

- packages/serverless-components/nextjs-cdk-construct/__tests__/__snapshots__/snapshots.test.ts.snap
- packages/serverless-components/nextjs-cdk-construct/src/index.ts
As per [this issue](https://github.com/serverless-nextjs/serverless-next.js/issues/2400), there are times during builds where the old `defaultNextLambda` gets destroyed before the build has completed and incoming traffic is served a 503 error for pages that have not yet finished static generation. 
Change the `removalPolicy` of `DESTROY` on the `defaultNextLambda` to `RETAIN`, and in a separate PR, trigger a function to clean up old Lambda's after a build has completed successfully.
> fix: Change defaultNextLambda removalPolicy from DESTROY to RETAIN

- packages/libs/aws-common/src/awsPlatformClient.ts
To reproduce:
- set `useV2Handle: true` in `serverless.yml`
- make sure the permission of the default lambda miss the `s3:GetObject` permission 
- run the default lambda using `getStaticProps`
Error is
```js
{
"errorType": "TypeError",
"errorMessage": "Converting circular structure to JSON\n    --> starting at object with constructor 'IncomingMessage'\n    |     property 'req' -> object with constructor 'ClientRequest'\n    --- property 'res' closes the circle",
"stack": [
"TypeError: Converting circular structure to JSON",
"    --> starting at object with constructor 'IncomingMessage'",
"    |     property 'req' -> object with constructor 'ClientRequest'",
"    --- property 'res' closes the circle",
"    at JSON.stringify (<anonymous>)",
"    at AwsPlatformClient.getObject …
```
> Handle V2, fix logging error when S3 permissions are not granted 
